version: "3"
services:
  scraper:
    build: .
    volumes:
      - .:/app
      - ./uploads:/app/uploads  # Persist uploaded files to host machine
    environment:
      - NODE_ENV=production
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium  # Point Puppeteer to Chromium path if installed separately
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true  # Skip downloading Chromium if using system-installed version
    networks:
      - default
    ports:
      - "5000:5000"  # Map the port (replace with your app's port if different)
networks:
  default:
    driver: bridge
