version: "3"
services:
  scraper:
    build: .
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    networks:
      - default
    ports:
      - "5000:5000"
    command: npm run dev
    # Add these to make Puppeteer run properly
    shm_size: '1gb'  # Prevent shared memory issues when launching Puppeteer
    cap_add:
      - SYS_ADMIN  # Allow Puppeteer to run with required privileges
    security_opt:
      - seccomp:unconfined  # Disable seccomp to allow sandboxing

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    networks:
      - default

networks:
  default:
    driver: bridge
